global:
  checkNewVersion: true
  sendAnonymousUsage: true
log:
  level: INFO
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
certificatesResolvers:
  dnsresolver:
    acme:
      email: serickson@ucsb.edu
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: route53
api:
  dashboard: false
providers:
  docker:
    exposedByDefault: false
