---
  - name: Install Coder on a VM
    hosts: all
    remote_user: admin
    become: true
    tasks:
    
    - name: apt upgrade
      become: true
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
    
    - name: install certbot
      become: true
      ansible.builtin.apt:
        pkg:
        - certbot
        - python3-certbot-dns-route53

    - name: install Coder
      become: true
      ansible.builtin.shell:
        cmd: curl -L https://coder.com/install.sh | sh
        creates: /root/.cache/coder/coder_*.deb
    
    - name: Coder config
      ansible.builtin.copy:
        owner: coder
        group: coder
        mode: '0644'
        dest: /etc/coder.d/coder.env
        content: |
          # /etc/coder.d/coder.env
          CODER_ACCESS_URL=https://coder.dreamlab.ucsb.edu
          CODER_WILDCARD_ACCESS_URL=*.coder.dreamlab.ucsb.edu
          CODER_TLS_ADDRESS=0.0.0.0:443
          CODER_HTTP_ADDRESS=0.0.0.0:80
          CODER_REDIRECT_TO_ACCESS_URL=true
          CODER_TLS_ENABLE=true
          CODER_TLS_CERT_FILE=/etc/coder.d/fullchain.pem
          CODER_TLS_KEY_FILE=/etc/coder.d/privkey.pem
          CODER_OIDC_ISSUER_URL="https://accounts.google.com"
          CODER_OIDC_EMAIL_DOMAIN="ucsb.edu"
          CODER_OIDC_CLIENT_ID="FIXME"
          CODER_OIDC_CLIENT_SECRET="FIXME"
          CODER_OIDC_ALLOW_SIGNUPS=false
  
    - name: cert deployment hook script
      ansible.builtin.copy:
        owner: root
        group: root
        mode: '0755'
        dest: /etc/letsencrypt/renewal-hooks/deploy/coder.sh
        content: |
          #!/bin/sh
          # /etc/letsencrypt/renewal-hooks/deploy/coder.sh
          certsdir="/etc/coder.d"
          domain="coder.dreamlab.ucsb.edu"
          basedomain="$(basename $RENEWED_LINEAGE)"
          youruser="coder"
          yourgroup="$(id -ng $youruser)"
          if [ "$domain" = "$basedomain" ];then
            cp "$RENEWED_LINEAGE/fullchain.pem" "$certsdir/fullchain.pem"
            cp "$RENEWED_LINEAGE/privkey.pem" "$certsdir/privkey.pem"
            chown $youruser:$yourgroup "$certsdir/fullchain.pem"
            chown $youruser:$yourgroup "$certsdir/privkey.pem"
            systemctl restart coder
          fi
    
    - name: create certs
      become: true
      ansible.builtin.shell:
        cmd: certbot certonly --dns-route53 -d coder.dreamlab.ucsb.edu -d *.coder.dreamlab.ucsb.edu --agree-tos -m serickson@ucsb.edu
        creates: /etc/letsencrypt/live/coder.dreamlab.ucsb.edu/cert.pem
    
    

